package com.automation.runners;

import io.cucumber.junit.CucumberOptions;
import net.serenitybdd.cucumber.CucumberWithSerenity;
import org.junit.runner.RunWith;

/**
 * RerunFailedRunner – re-runs only the scenarios that failed in the previous run.
 *
 * Usage:
 *   1. Run main suite:      mvn verify -Drunner=TestRunner
 *   2. Rerun failures:      mvn verify -Drunner=RerunFailedRunner
 *
 * Reads from target/cucumber-reports/rerun.txt generated by @rerun plugin.
 */
@RunWith(CucumberWithSerenity.class)
@CucumberOptions(
        features = "@target/cucumber-reports/rerun.txt",
        glue = {
                "com.automation.steps",
                "com.automation.config"
        },
        plugin = {
                "pretty",
                "json:target/cucumber-reports/cucumber-rerun.json",
                "html:target/cucumber-reports/cucumber-rerun.html"
        },
        monochrome = true
)
public class RerunFailedRunner {
    // Intentionally empty
}
